### PR TITLE
gulp minify update

### PR DESCRIPTION
**Pull request by joshuafbarker**
Moved non minified version to src folder. Added gulp file, with minify
task. Added package.json with dev dependencies. Added gitignore file to
exclude node_modules folder, and .DS_Store file.

### CODE REVIEW

**Comment by laszlof** [comment]
Looks like theres a merge conflict (I Updated the .min.js file). Please resolve this and I'll go ahead and take a look.

**Comment by joshuafbarker** [comment]
I ran the minifier task, so it might have rendered it slightly different than the current version.

**Comment by laszlof** [comment]
Thats fine. You can replace the file, you just need to update the PR to match it :)

**Comment by joshuafbarker** [comment]
Alright, should be good to go.

**Pull request merged**
