### PR TITLE
Removed the need for jQuery

### PR DESCRIPTION
**Pull request by joshuafbarker**
jQuery is no longer needed for this!

I didn't minify it, if you would like me to I could.

### CODE REVIEW

**Comment by laszlof** [comment]
Thanks! Will take a look tomorrow and comment/merge/etc.

**Comment by laszlof** [comment]
Can you please remove additional `console.log` statements, and the mac droppings (.DS_Store file)? Thanks

**Comment by laszlof** [comment]
As far as minifying goes. I think I'll make another task for doing that automatically, perhaps via bower or grunt.

**Comment by joshuafbarker** [comment]
Good deal. Should be good to go now!

**Comment by laszlof** [comment]
Sorry, one last thing. Please remove the commented out line in the example file. Thanks!

**Comment by joshuafbarker** [comment]
Haha, no problem! Done.

**Pull request merged**
